package com.prahlad.aijobportal.aiservice.recommendation.dto.response;

import java.util.List;
import java.util.UUID;

/**
 * A recruiter-facing ranked applicant for one job. Unlike
 * {@link JobRecommendationResponse}, this is never persisted — the
 * applicant pool for a job changes too frequently (new applications
 * arrive continuously) for a stored ranking to stay meaningful, so it
 * is recomputed on each request and only cached briefly (see
 * {@code CANDIDATE_RECOMMENDATIONS_CACHE}).
 *
 * <p>{@code strengths}, {@code weaknesses}, {@code missingSkills}, and
 * {@code hiringRecommendation} are per DAY10_AI_Enhancement_ATS_Intelligence.md's
 * "Recruiter Candidate Match" section, generated by Gemini alongside
 * the shared match breakdown/reasoning.
 */
public record CandidateRecommendationResponse(
        UUID applicationId,
        UUID candidateId,
        String candidateName,
        int matchScore,
        MatchBreakdownResponse matchBreakdown,
        List<String> reasoning,
        List<String> strengths,
        List<String> weaknesses,
        List<String> missingSkills,
        String hiringRecommendation
) {
}
